"use strict";
exports.__esModule = true;
var User_1 = require("./User");
exports.User = User_1["default"];
var Exam_1 = require("./Exam");
exports.Exam = Exam_1["default"];
var ExamReturn_1 = require("./ExamReturn");
exports.ExamReturn = ExamReturn_1["default"];
var mcqQuestion_1 = require("./mcqQuestion");
exports.MCQuestion = mcqQuestion_1["default"];
var QuestionAnswer_1 = require("./QuestionAnswer");
exports.QuestionAnswer = QuestionAnswer_1["default"];
var AggregateExamResult_1 = require("./AggregateExamResult");
exports.AggregateExamResult = AggregateExamResult_1["default"];
var AggregateExamQuestionAnalysis_1 = require("./AggregateExamQuestionAnalysis");
exports.AggregateExamQuestionAnalysis = AggregateExamQuestionAnalysis_1["default"];
